-- AlterTable
ALTER TABLE `company` ADD COLUMN `companySize` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `industry` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `logo` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `website` VARCHAR(191) NOT NULL DEFAULT '';
